### ISSUE TITLE
Any issue available to contribute? GSSOC23 Contributer here.

### ISSUE THREAD

**Issue by s0oraj** [Yash-Parsana/CrazyCoderApp#1]
Hi @Yash-Parsana  , i am a GSSOC23 contributer and I would like to resolve any issue you might have.
I have seen this project from project section of GSSOC23

Can you assign some issue?
Heres My Resume which you might find useful: [Resume](https://github.com/codervivek5/VigyBag/files/11521351/Resume.pdf)
Ive more than 1 year of experience in android development(check profile for more details)

**Comment by Yash-Parsana** [comment]
@s0oraj 
Yes it has some issues i will mention it soon.
Just for now try to understand project and download app from PlayStore for better understanding.

**Comment by Aditya13s** [comment]
Hi @Yash-Parsana ,  I am a GSSOC23 contributor
I'm eager to contribute to this project and utilize my Android development skills. I'm looking for new issues to work on or opportunities to implement new features. If there are any tasks that need assistance or if you have any specific feature requests, I would be happy to contribute.

Please let me know if there are any unassigned issues or if you would like me to propose new features or improvements to the project. I'm open to suggestions and ready to collaborate with the team.

Thank you, and I'm excited to be part of this project!
