### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [Yash-Parsana/CrazyCoderApp#11]
I would like to work on improving the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Yash-Parsana** [comment]
what you will do exactly?

**Comment by harshsingh32** [comment]
I would like to improve the readme file making it more expressive, using catchy phrases and making it more expressive using colourful symbols. I would like to add some features and making it engaging for the users, so the engagement of the project increase and contribution of the project increase.

**Comment by Yash-Parsana** [comment]
@harshsingh32 
You are assigned this issue under GssoC'23
Thank You
