### ISSUE TITLE
Improving the logo design 

### ISSUE THREAD

**Issue by harshsingh32** [Yash-Parsana/CrazyCoderApp#12]
I would like to work on improving the logo design of this project making it engaging and more expressive. I would like to add some features and improve it making more colorful and vibrant.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Yash-Parsana** [comment]
@harshsingh32 
You may work on this but it is not guaranteed that your logo will be used in production.

**Comment by harshsingh32** [comment]
Sure, I will improve the design of the logo, making it more vibrant that makes your project inspiration and values. If you have any specific suggestions on the type of colours to be used in the new design, you can acknowledge me. I will definitely provide you better design then the one you are using.

**Comment by Yash-Parsana** [comment]
use blue,white and black colour

**Comment by Yash-Parsana** [comment]
Currently i am closing this issue you may recreate it after merge of issue #11
