### ISSUE TITLE
Adding a contribution.md

### ISSUE THREAD

**Issue by harshsingh32** [Yash-Parsana/CrazyCoderApp#13]
I would like to add a contribution.md to the project, It will improve the contribution of the users in the project and engagement of this project increase.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by Yash-Parsana** [comment]
This issue is assigned to @harshsingh32 under GssoC'23

**Comment by utkarsh006** [comment]
@Yash-Parsana Can I work under this issue. A contributor can work for one issue at a time, according to rules.

**Comment by Yash-Parsana** [comment]
@utkarsh006 
Yes, You are assigned this issue under GssoC'23

**Comment by harshsingh32** [comment]
Sir, I would like to work on this issue, I have relevant experience and skillset to resolve the issue. I would like to improve contribution.md.

**Comment by Yash-Parsana** [comment]
@harshsingh32 You are already assigned two issues so work on them.

**Comment by shanvijha30** [comment]
@Yash-Parsana could you please assign this issue to me.
Thank you!

**Comment by Yash-Parsana** [comment]
i am creating new issue.
comment on that if you want to work on it.

**Comment by shanvijha30** [comment]
@Yash-Parsana I have created a new issue [#47](https://github.com/Yash-Parsana/CrazyCoderApp/issues/47) 
you can assign this issue to me.
