### ISSUE TITLE
Strong Password Check

### ISSUE THREAD

**Issue by Yash-Parsana** [Yash-Parsana/CrazyCoderApp#14]
Implement functionality of Strong Password check in sign up activity.
Password requirenment :
1.Lenght shoud be at least 12 characters
2.Contain atleast one Capital Alphabet
3.Contain atleast one small Alphabet
4.Contain atleast one symbole Alphabet

**Comment by shags8** [comment]
Please assign me this , I will be able to implement it .

**Comment by Yash-Parsana** [comment]
@shags8 
This issue is assigned to you under gssoc'23

**Comment by akshmangal005** [comment]
@ @Yash-Parsana please assign me this issue

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @Yash-Parsana , I would like to work on this. As i already have experience in creating a strong password checker app. As it is already assigned to someone. I believe he will come up with a good solution. If there is any major again i will try my best to rectify it.

**Comment by shags8** [comment]
> Hi @Yash-Parsana , I would like to work on this. As i already have experience in creating a strong password checker app. As it is already assigned to someone. I believe he will come up with a good solution. If there is any major again i will try my best to rectify it.

@Ashok-Kumar-dharanikota you can work on it . As I am not free i will not be able to complete it.

**Comment by Ashok-Kumar-dharanikota** [comment]
@shags8 thank you for letting me know. You already done ✅ your best 👍.

**Comment by Ashok-Kumar-dharanikota** [comment]
> Implement functionality of Strong Password check in sign up activity.
> Password requirenment :
> 1.Lenght shoud be at least 12 characters
> 2.Contain atleast one Capital Alphabet
> 3.Contain atleast one small Alphabet
> 4.Contain atleast one symbole Alphabet

Hi @Yash-Parsana , 

I solved this issue, if you assign me this. I will create a PR along with the video.

**Comment by Yash-Parsana** [comment]
@Ashok-Kumar-dharanikota 
This issue is assigned to you under GssoC'23.
