### ISSUE TITLE
Implement MVVM Architecture.

### ISSUE THREAD

**Issue by Yash-Parsana** [Yash-Parsana/CrazyCoderApp#15]

**Comment by mad-alpha** [comment]
Can you please assign this issue to me under GSSoC'23 tag? @Yash-Parsana

**Comment by Aditya13s** [comment]
Please assign me this task i have a good experience with the Mvvm architecture.
@Yash-Parsana

**Comment by Yash-Parsana** [comment]
@mad-alpha @Aditya13s 
it is critical task for this project so describe why should i assign you this task with facts and proofs.

**Comment by harsh2907** [comment]
Well I've been working with MVVM architecture for a long time, you can check my github for projects i have used MVVM there and also used best practices to make code testable and also follows SOLID principle , and for proofs my projects are there on my github. And also i have raised this issue yesterday also before anyone else so please assign this task to me

**Comment by Tejas-67** [comment]
Please assign this task to me under Gssoc'23 I am very well versed with MVVM structure and i will structure the code very well so that it can be easily maintained and scaled in the future.

**Comment by Aditya13s** [comment]
@Yash-Parsana can you assign me this task or you can assign 2 or more peoples on it if this is a complex task

**Comment by Yash-Parsana** [comment]
Currently i am putting this issue on hold. try to solve other issue and prove your credibility and according to performance i will assign this issue.
