### ISSUE TITLE
The app hangs when we go from any other activity to leaderboard

### ISSUE THREAD

**Issue by iampranshu2003** [Yash-Parsana/CrazyCoderApp#16]
Whenever we try to go to leaderboard from any other activity the app hangs and stops working.
If you go to leaderboard directly it works but when you change the activity and again try to go to leaderboard tab the app
will hang and you have to restart the app again.

https://github.com/Yash-Parsana/CrazyCoderApp/assets/116300962/48228d2f-7c22-44fe-8405-2f4b6f800809

**Comment by iampranshu2003** [comment]
I want to contribute to this issue please assign this issue to me under ggsoc tag .

**Comment by harsh2907** [comment]
I've already mentioned this issue on yesterday's afternoon

**Comment by Yash-Parsana** [comment]
This issue is already solved in Local Repo
