### ISSUE TITLE
Code CleanUp

### ISSUE THREAD

**Issue by nishkarsh800** [Yash-Parsana/CrazyCoderApp#18]
- To clean up the code to increase the readability

**Comment by Yash-Parsana** [comment]
@nishkarsh800 
What you will do under this issue ?
which file will be modified ?

**Comment by nishkarsh800** [comment]
- Under this issue I'll reformat the code

**Comment by Yash-Parsana** [comment]
@nishkarsh800 You are assigned this issue.
Stay focused while working on because small mistake can cause big problem.
i will decide issue level after seeing your work.

**Comment by nishkarsh800** [comment]
Sure

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by Yash-Parsana** [comment]
Are you working on it ? @nishkarsh800

**Comment by nishkarsh800** [comment]
Yes I'm working
