### ISSUE TITLE
Spell Check

### ISSUE THREAD

**Issue by nishkarsh800** [Yash-Parsana/CrazyCoderApp#2]
- There are some spelling mistakes in some files and UI in the app.
- Assign me this issue under GSSOC'23.

**Comment by Yash-Parsana** [comment]
@nishkarsh800 
can you point out some of them ?

**Comment by nishkarsh800** [comment]
- Some File names and spellings in UI such as Email address

**Comment by nishkarsh800** [comment]
- Are you going to assign me?

**Comment by Yash-Parsana** [comment]
I think it is not big issue but its solution can create big issues so currently closing it. Try to solve other issues.
I hope you don't mind.
Thank You.
