### ISSUE TITLE
To implement Icon

### ISSUE THREAD

**Issue by nishkarsh800** [Yash-Parsana/CrazyCoderApp#23]
- To implement Icon for Showing password while signup and signin

**Comment by Yash-Parsana** [comment]
@nishkarsh800 
You are assigned this issue under GssoC'23

**Comment by Yash-Parsana** [comment]
Are you working on this ?
or i should close it.

**Comment by ashupandey1620** [comment]
Can you please Assign it to me under GssoC'23?
I will add the icons in their best form to this project.

**Comment by nishkarsh800** [comment]
@Yash-Parsana , I'm working on this

**Comment by VishalVinayRam** [comment]
can i work on this

**Comment by oshinsaraf** [comment]
Can you assign me this under GSSOC'23?
