### ISSUE TITLE
Custom 404 Page

### ISSUE THREAD

**Issue by jaskaranl** [Yash-Parsana/CrazyCoderApp#26]
I will design an Error Page for calls or redirecting to pages which do not exist.

Hello!
I am Jaskaran Kamboj, a proud contributor at GSSoC '23. I would like to the contribute to this project by designing an Error Page for calls or redirecting to pages which do not exist.

Things I will be doing as of now:

 Designing the error page 404

**Comment by Yash-Parsana** [comment]
As per now there is no need of this page.
