### ISSUE TITLE
Enhancing the UI of the signup page

### ISSUE THREAD

**Issue by NehaVns** [Yash-Parsana/CrazyCoderApp#27]

**Comment by Yash-Parsana** [comment]
Can you show what will be the final output?

**Comment by NehaVns** [comment]
**Disclaimer: This is not the final output.**
<img width="147" alt="image" src="https://github.com/Yash-Parsana/CrazyCoderApp/assets/95272322/0263dc6c-9516-42f2-900c-90f85c77b71c">

This is a demo. Basically, I will be adding the icons and designing some drawable resource files to shape the EditText view. And all this will be according to the dark theme. There will be some other changes as well.

**Comment by Namanbansal06** [comment]
I can add a better UI for signup page. pls assign it to me.

**Comment by Namanbansal06** [comment]
I can make a better UI for Signup page. I will add vectors and logo in signup page.

**Comment by Yash-Parsana** [comment]
just add icons in input fields no other changes.
This issue is assigned to @NehaVns under gssoc'23.

**Comment by MUDITJAINN** [comment]
please assign this issue to me as I can make it dynamic with animations and make it more interactive and attractive.

**Comment by Sixpcoder** [comment]
please assign the issue to me ,I will make it more classy and simplistic and can add animation to it.please provide it under the gssoc label

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by chhavisharma30** [comment]
I can work on thi issue as  I have previous internship experience as an android developer. Can you assign me this issue?

**Comment by Yash-Parsana** [comment]
I think Signup ui is fine. Closing this isssue
