### ISSUE TITLE
Improve Sign In page

### ISSUE THREAD

**Issue by RashakDude** [Yash-Parsana/CrazyCoderApp#36]
Hey @Yash-Parsana, 

Wishing to add sign-in option using Google, Facebook and Github. 
Also wanted to improve the UI of login page to somewhat like [this](https://dribbble.com/shots/8759887-Mobile-app-Login-Signup-UI-concept)
Would like to work on it for GSSOC

**Comment by Yash-Parsana** [comment]
signin with Facbook and github is not required in this project
