### ISSUE TITLE
Google Signin feature not working 

### ISSUE THREAD

**Issue by harsh2907** [Yash-Parsana/CrazyCoderApp#39]
In the code when i try to signin with google that account selection dialog shows up but on selecting the account it gives RESULT_CANCELLED instead of RESULT_SUCCESS so can anyone help me with it I've to work upon it

**Comment by Tejas-67** [comment]
I can do this! please assign this task to me.

**Comment by harsh2907** [comment]
Brother I'm asking out fir help this issue is already assigned for me i was just stuck so i mentioned it here

**Comment by LaveshK11** [comment]
@harsh2907  i can help you with that dm me on discord lavesh#9588

**Comment by harsh2907** [comment]
Sent you friend request!

**Comment by Yash-Parsana** [comment]
Try to reachout mentor of this project @Pranshu1902. Nowadays i am little busy.

**Comment by ayush290104** [comment]
Are you working on this issue?

**Comment by harsh2907** [comment]
What can be the possible reason for this, if you can tell me it would be a great help

**Comment by imharshitg07** [comment]
I would like to work on this issue. Please assign this to me
