### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [Yash-Parsana/CrazyCoderApp#4]
I want to add readme badges .Please assign this issue to me under GSSOC
![badges](https://github.com/Yash-Parsana/CrazyCoderApp/assets/104543751/24e6512c-9e55-420a-b1c0-667f9edb56a9)

**Comment by peculiaruc** [comment]
Hi @S-ishita I am working on this issue. Kindly assign it to me

**Comment by Yash-Parsana** [comment]
@S-ishita you are assigned this issue.

**Comment by S-ishita** [comment]
> @S-ishita you are assigned this issue.

You forgot to add as assignee .... @Yash-Parsana
