### ISSUE TITLE
Add Code of conduct.md

### ISSUE THREAD

**Issue by tayyab-ilyas** [Yash-Parsana/CrazyCoderApp#40]
A code of conduct serves as a framework that defines the expected standards of behavior and engagement. It plays a pivotal role in cultivating an inclusive and welcoming environment that values and respects the contributions of all participants. The code of conduct also provides clear guidelines and procedures for addressing any issues, conflicts, or concerns that may arise among members of the open source project's community.

**Comment by tayyab-ilyas** [comment]
hey @Yash-Parsana,  can you assign me this under GSSoc'23, thanks!

**Comment by Yash-Parsana** [comment]
I think Contribution Guidelines is enough.
