### ISSUE TITLE
Add Landscape mode .

### ISSUE THREAD

**Issue by Namanbansal06** [Yash-Parsana/CrazyCoderApp#43]

**Comment by Yash-Parsana** [comment]
@Namanbansal06 
This issue is assigned to @Namanbansal06 under gssoc'23.
but you have to make full video after implementation showing all features are working fine.

**Comment by Namanbansal06** [comment]
Give me your discord I'd or mail so that I can share you the video of my work.

**Comment by Yash-Parsana** [comment]
You can share it with PR.

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??
