### ISSUE TITLE
Overall Update of the ReadMe with Markdown standard

### ISSUE THREAD

**Issue by peculiaruc** [Yash-Parsana/CrazyCoderApp#45]
I will improve the ReadMe to include the following:

- The README file will be updated to meet Markdown Standard.
- Add the 'how to contribute to this project' section (The Contributors Section).
- Add Technologies used for this project with badges of each technology.
- Add Code of Conduct on the ReadMe
- Add the necessary badges and links to the Readme.
- Write guidelines on How to Make Your First Pull Request,
- Add App Screenshots/Images.

Please assign it to me under GSSoC'23.

**Comment by peculiaruc** [comment]
> Issue: The README file is yet the meet the Markdown Standard
> 
> * The README file can be updated with Markdown Standard.
> * Add the 'how to contribute to this project' section.
> * Add features like Technology used for this project.
> 
> Please assign it to me under GSSoC'23.

**Comment by peculiaruc** [comment]
@Yash-Parsana Kindly assign this issue to me

**Comment by Yash-Parsana** [comment]
i am creating new issue.
comment on that if you want to work on it.

**Comment by peculiaruc** [comment]
Sure I want to work on it. Assign me please
