### ISSUE TITLE
Major Bug: App freeze !!!

### ISSUE THREAD

**Issue by Ashok-Kumar-dharanikota** [Yash-Parsana/CrazyCoderApp#46]
Hi @Yash-Parsana,

I downloaded the Crazycoder App from Playstore and while testing the application, I encountered a major issue. The problem occurs when navigating through the bottom navigation bar, specifically when accessing the Leaderboard button for the second time. The app freezes in this situation, requiring the user to close and reopen it to continue. This creates a poor user experience. Therefore, I would like to take on the task of fixing this bug as soon as possible. Kindly assign me this issue, as it is a significant problem that needs immediate attention. Please add Bug and GSSoC23 Tag for this.

- [x] Bug
- [x] GSSoC23

screenshot:
![WhatsApp Image 2023-05-23 at 19 18 08](https://github.com/Yash-Parsana/CrazyCoderApp/assets/103619560/6cdc5fc1-5b3d-4f4d-b1f5-aa1575b8adf1)

**Comment by Yash-Parsana** [comment]
it is already solved in local codebase.
Thank You.

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @Yash-Parsana , thank you for letting me know. Please let me know if there are any panding issues for long time. I will work on it. 😉
