### ISSUE TITLE
Add LICENCE

### ISSUE THREAD

**Issue by Jiggy9** [Yash-Parsana/CrazyCoderApp#49]
Hey, @Yash-Parsana   I'm active GSSoC'23 contributor and I would like to add a license file to this repository. Please assign me to this issue. Thank you!

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by Yash-Parsana** [comment]
You are assigned this issue @Jiggy9 under gssoc23
