### ISSUE TITLE
Sign in with google doesn't work

### ISSUE THREAD

**Issue by harsh2907** [Yash-Parsana/CrazyCoderApp#5]
In the release version of this app, Sign in with google doesn't work on the sign up screen if we dont put our username ,We can create a sort of dialog box or asked for the username after successful sign in with google that would give a great user experience. So assign this issue to me i will fix this.

**Comment by AKsHaT123456A** [comment]
Hi @Yash-Parsana can you assign me this issue..?

**Comment by Yash-Parsana** [comment]
Hello @AKsHaT123456A 
Username is mandatory to signup without selecting username no one can signup.
So it is not an issue

**Comment by harsh2907** [comment]
Don't you think it's quite odd that user have to insert username only in fields while skipping others while logging in, so if we ask for username later by adding a second screen that would be great that's what i proposed

**Comment by Yash-Parsana** [comment]
@harsh2907 
Okay you may work on it.
User comes to sign up activity sign up with google or email after successful signup user will be redirected to new activity where user have to choose unique user name and then user redirected to main activity. Note that user can not access main activity(home page) or other features of app without selecting username.

After successful implementation please make video and share with PR.
Thank You

**Comment by Yash-Parsana** [comment]
Also consider some scenarios which might cause problems like after successful signup user registered in databse -> now user redirected on username selection activity -> user don't select username and close app -> now user come back and try to login since user is registered in database user can login and can access main activity which is not allowed.

**Comment by Yash-Parsana** [comment]
@harsh2907 
Are you working on it ?

**Comment by AKsHaT123456A** [comment]
Hi @Yash-Parsana if it's okay I am interested to resolve this issue

**Comment by Yash-Parsana** [comment]
@harsh2907 solve it by this sunday otherwise will be assigned to other contributor.

**Comment by harsh2907** [comment]
My friend can't you see i've been asking for help for last 4-5 days but you are giving no reply i've been asking why the signin/sign up doesnt work but you are not replying

**Comment by harsh2907** [comment]
Assign it to some one else along with all the issues that I've assigned myself because if you can't help us then whats the meaning of your being mentor

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi, @harsh2907!

We can observe in some apps that by using Google Sign-in, they can retrieve our username. By applying Regex or a custom username pattern, we can create a random username for the user by combining the Gmail username and our pattern. Then, we can provide the user with the option to change their username or keep it as it is. This approach would be better if the username, email, and password need to be provided all at once and user also doesn't need to spend much time on this. happy to help you with this.

**Comment by harsh2907** [comment]
@Ashok-Kumar-dharanikota  thanks for the help mate! but please refer to issue #39 you can understand my problem that I'm facing for last 4-5 days

**Comment by harsh2907** [comment]
@Yash-Parsana Assign the issues related to sign in from me to others because i am facing same problem while i can work on Dagger Hilt , MVVM , package structuring and other ui stuff so you can assign those to me the once that are on hold like #10 #15 #25 anyone would be great

**Comment by javaman97** [comment]
@harsh2907 Thanks for mentioning the issue but I would be happy to resolve my own issue

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by Yash-Parsana** [comment]
This issue is assigned to @priyanshu942 under Gssoc23
