### ISSUE TITLE
Adding onboarding and intro slides

### ISSUE THREAD

**Issue by jaivsh** [Yash-Parsana/CrazyCoderApp#51]
**Suggestion:**
I'd add a proper onboarding experience for new users, so that they'd get acquainted with the application in an easy manner. Apart from that, I'd also design and implement the intro slides for the app, which would get executed during the first run. 

**Sample screenshots of onboarding and intro slides:**

![](https://camo.githubusercontent.com/bad7e3d3a53cd264e4a4be2383c233ebedca1888d13ad35fe8b67b36e3561072/68747470733a2f2f75706c616e64736f6674776172652e636f6d2f6c6f63616c79746963732f77702d636f6e74656e742f75706c6f6164732f73697465732f34352f323032302f30362f6170702d757365722d6f6e626f617264696e672e706e67)

![](https://camo.githubusercontent.com/7f5681e0a9f58163c9fe6172bf7abcbd2e3afd7618e9f08f6f9c76a66befd9ce/68747470733a2f2f7777772e6461746f636d732d6173736574732e636f6d2f34383239342f313636303839383638362d6d61642d6f6e626f617264696e672d392d696d706163742e706e673f6175746f3d666f726d6174)

**Comment by Yash-Parsana** [comment]
You are assigned this issue under GssoC'23 
use colours that match with app theme.
you have to share video of implemented feature with PR.

**Comment by jaivsh** [comment]
Hello @Yash-Parsana 
I've linked a PR with the issue. Can you please check for the same? 
Thanks!
