### ISSUE TITLE
Data lost while switching between the tabs.

### ISSUE THREAD

**Issue by Namanbansal06** [Yash-Parsana/CrazyCoderApp#53]
when we switch between the tabs. the data gets lost and it restart the loading which takes lots of time to load.

**Comment by oshinsaraf** [comment]
Hey, could you assign me this issue? I'd love to work on it under GSSOC'23.

**Comment by Namanbansal06** [comment]
Assign me this issue so that I can start my work on it Asap

**Comment by Namanbansal06** [comment]
@Yash-Parsana Assign me this issue so that i can solve this bug.

**Comment by Yash-Parsana** [comment]
i think this issue should present in schedule fragment because i already implemented solution in leaderboard fragment. Right ?

**Comment by Namanbansal06** [comment]
According to my updated version of the app...the data lost state happens in all the fragments (i.e. leaderboard fragment, scheduling fragment) and leaderboard fragment goes to indefinite loading on several swipes between the fragments.
