### ISSUE TITLE
Adding Redirecting feature to easily register for any contest!!!

### ISSUE THREAD

**Issue by Ashok-Kumar-dharanikota** [Yash-Parsana/CrazyCoderApp#57]
Hi @Yash-Parsana,

I would like to work on implementing the redirecting feature. Simply, if the user wants to participate in some particular contest. By clicking on the contest text or whole item he moved to New activity where it contains additional information about the contest. If we want to participate in the contest. By clicking on the Register button. He redirected to the web page where he can register to the contest. 

This way, We are saving time for the user and making him not procrastinate the contest or event. 

It may involve with the server side too. I truly appreciate your feedback on this. If you preferring any other issues or features before we move to this one. Please let me know so i would work on them first. 

Thank you 😊

- [x] GSSOC 23

**Comment by Yash-Parsana** [comment]
It lots of server side and client side work and also it will take good amout of time so closing it.
