### ISSUE TITLE
Make a good splash screen.

### ISSUE THREAD

**Issue by Namanbansal06** [Yash-Parsana/CrazyCoderApp#58]
Make a spalsh screen with animation effect just like Netflix splash screen.

![image](https://github.com/Yash-Parsana/CrazyCoderApp/assets/97379101/94cc5166-908e-4e7b-8435-eaf5613e5e3f)

**Comment by khan-mujeeb** [comment]
I would like to work on this issue

**Comment by khushichauhan05** [comment]
I would like to work on this issue.Plz assign this to me under gssoc

**Comment by ritz-17** [comment]
i would like to work on this issue . Pls assign me this

**Comment by MUDITJAINN** [comment]
I would like to work on it as this task fits me right and also It would be a great start for me as a Gssoc'23 contributor please assign me this issue.

**Comment by imharshitg07** [comment]
I would like to work on this issue. Please assign this to me

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by Yash-Parsana** [comment]
This issue is assighed to you @Namanbansal06

**Comment by crsongirkar** [comment]
Hello sir I am Interested in This Task. I have already created some splash screen and onboarding screen. please assign me  under the GSSOC'23
