### ISSUE TITLE
Leaderboard section freezes Ui

### ISSUE THREAD

**Issue by harsh2907** [Yash-Parsana/CrazyCoderApp#6]
On visiting the leaderboard section from bottom nav for first time it will show nothing but on visiting second time ot freezes the ui and loads indefinitely. It should show the data/ loading the data on first visit itself.
I want to fix this issue so kindly assign it to me under GSSOC'23

**Comment by Yash-Parsana** [comment]
@harsh2907 
i have intentionally put ui freeze on leaderboard fragment i think it is not issue if you still think its an issue please describe it with short video.
Thank you
