### ISSUE TITLE
Feature Request: Designing a website for "CrazyCoderApp"

### ISSUE THREAD

**Issue by yaten2302** [Yash-Parsana/CrazyCoderApp#72]
Hi @Yash-Parsana,  was having an idea of designing a website for "CrazyCoderApp" would be a great idea?

The app is very useful for Competitive Programming competition updates . I think that if there is a website for this, then it will attract more and more users.

**Describe the solution you'd like**

Here all the details of this app will be added with some demo screenshots, videos, features and some description about the app.
Also there can be a "Contact page" and "FAQs section". This will be easier for the user to get to know about the project very easily.

Also it will attract more users because of the beautiful UI of the website and the app.

Please assign this task to me under GSSOC'23, as I want to work on this issue 🙏
I will start making the prototype and the website once you approve.

**Comment by oshinsaraf** [comment]
Can I work on this under GSSOC'23 with you? We could make a fully functional website adding multiple features.

**Comment by Yash-Parsana** [comment]
You are assigned this issue under Gssoc'23 @yaten2302 which tech stack you will use ?

**Comment by Yash-Parsana** [comment]
try to make it in javascript if it is possible.

**Comment by yaten2302** [comment]
Hi @Yash-Parsana, I will be using HTML, CSS and JavaScript

**Comment by Yash-Parsana** [comment]
I was talking about backend (NodeJs)

**Comment by yaten2302** [comment]
Sorry, I didn't get what you are trying to tell, could you please explain again 🙏

**Comment by oshinsaraf** [comment]
I have experience in node.js and i could help with the backend part.

**Comment by yaten2302** [comment]
Actually I don't know node.js, so I will not be able to use it 😥

**Comment by Yash-Parsana** [comment]
@yaten2302 Then make static website Thank You

**Comment by yaten2302** [comment]
Hi @Yash-Parsana, I have made the website, only the contact page is left, could you please send your socials so that I can put them in the website.

**Comment by Yash-Parsana** [comment]
LinkedIn: https://www.linkedin.com/in/yash-parsana-a9176a1b2/
playstore: https://play.google.com/store/apps/details?id=com.parsanatech.crazycoder
