### ISSUE TITLE
Adding auto_comment.yml file

### ISSUE THREAD

**Issue by Anshika-Jain02** [Yash-Parsana/CrazyCoderApp#76]
*We need to add an auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively. This will promote motivation and performance*

@Yash-Parsana Please assign me this issue under gssoc'23

**Comment by Nishitbaria** [comment]
hey @Anshika-Jain02  I have Already Created issue Checkout  :https://github.com/Yash-Parsana/CrazyCoderApp/issues/63

**Comment by Yash-Parsana** [comment]
duplicate #63
