### ISSUE TITLE
Integrate CI/CD for automating the tasks

### ISSUE THREAD

**Issue by khan-mujeeb** [Yash-Parsana/CrazyCoderApp#78]
### Is your feature request related to a problem? Please describe.

We need to integrate CI/CD  as it helps us to automatically release new apk whenever we merge any PR to LATEST_VERSION branch

@Yash-Parsana please assign me this issue under gssoc'23.

### Describe the solution you'd like

I will use github actions for automating this task

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Yash-Parsana** [comment]
Sorry I don't want this feature for some reason.
