### ISSUE TITLE
Update Dependency 

### ISSUE THREAD

**Issue by harsh2907** [Yash-Parsana/CrazyCoderApp#8]
We can update the gradle dependency to latest version i.e 8.0.1 and also kotlin version from 1.7 to 1.8.21  to enable latest features of kotlin and also update dependency versions in build.gradle and also update the target sdk version to latest to make app supported in latest version of android

**Comment by harsh2907** [comment]
So kindly assign this issue to me

**Comment by Yash-Parsana** [comment]
You are assigned this issue under GssoC'23

**Comment by harsh2907** [comment]
Done PR you can check and merge it

**Comment by Yash-Parsana** [comment]
Hello @harsh2907 
Please Pull updated master branch and make another PR. don't forget to create new branch.
Sorry for inconvenience.

**Comment by harsh2907** [comment]
ok no problem
