### ISSUE TITLE
Full Stack Website for the crazy code app

### ISSUE THREAD

**Issue by Kushagra102** [Yash-Parsana/CrazyCoderApp#84]
### Is your feature request related to a problem? Please describe.

The app currently does not have a marketing or web-app type website.

### Describe the solution you'd like

To create such a website or a Web-APP powered by the same express backend.

### Describe alternatives you've considered

Using React, and beautiful animations for the site.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Yash-Parsana** [comment]
You are assigned this issue under Gssoc23.
focus on attractive UI.
There is a website folder in repo in that folder make another folder and keep you word there.
Thank You.

**Comment by Yash-Parsana** [comment]
In website folder you will find one website make one folder and move the code in that folder
Folder structure look like
website
     - Web1 -> contain existing website code
     - Web2 -> Your website code
 
Thank You

**Comment by Kushagra102** [comment]
Done working on it. Have exams till 2nd will be done by 5th most probably.

**Comment by Yash-Parsana** [comment]
@Kushagra102 
Kindly deploy it on vercel / netlify serverless function.

**Comment by Kushagra102** [comment]
Okay 👍🏼

**Comment by Yash-Parsana** [comment]
Hello @Kushagra102 Have you completed this task ?

**Comment by Kushagra102** [comment]
Got delayed because of exams, will be making a pr by 10 most probably.
