### ISSUE TITLE
Add Code of Conduct.md

### ISSUE THREAD

**Issue by smty2018** [Yash-Parsana/CrazyCoderApp#85]
### Is your feature request related to a problem? Please describe.

want to add code of conduct.md file to this repo
@Yash-Parsana can you please assign it to me under gssoc 23

### Describe the solution you'd like

want to add code of conduct.md file to this repo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashim1588** [comment]
Hey,
Please let me write codeofconduct.md
