### ISSUE TITLE
Adding a share app feature in profile page

### ISSUE THREAD

**Issue by jaivsh** [Yash-Parsana/CrazyCoderApp#87]
### Is your feature request related to a problem? Please describe.

I'd implement a share the application feature in the profiles page, which would launch a share intent that would share application and rhymes to wider potential users.

### Describe the solution you'd like

I'd use the share intent to share the app in aviliable platforms on user's device. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jaivsh** [comment]
@Yash-Parsana please assign me this! Thanks

**Comment by Yash-Parsana** [comment]
Can you share design of the feature means how it will look ?

**Comment by chhavisharma30** [comment]
I can implement this. Kindly assign me this issue.
