### ISSUE TITLE
Update readme 

### ISSUE THREAD

**Issue by Shikhar9425** [Yash-Parsana/CrazyCoderApp#89]
### Is your feature request related to a problem? Please describe.

Wants to add some more features and wants to make readme more impressive

### Describe the solution you'd like

Wants to add some more features and wants to make readme more impressive

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shikhar9425** [comment]
@Yash-Parsana please assign me this issue

**Comment by Yash-Parsana** [comment]
What features you want to add ?

**Comment by Shikhar9425** [comment]
> What features you want to add ?

Features about crazy coder App other than that you have already mentioned and wants to make readme more impressive @Yash-Parsana

**Comment by Yash-Parsana** [comment]
What you exactly want to do ?

**Comment by Shikhar9425** [comment]
1. add more features other than that you have mentioned.
2. wants to add some more content to the description so that it will be more easily understandable.
3. align/modify some of the headings .
4. wants to make an impressive readme 
 @Yash-Parsana

**Comment by Yash-Parsana** [comment]
I think current readme has this all features so i am clossing this issue.
Thank You
@Shikhar9425
