### ISSUE TITLE
Docs - Adding a MIT Licenses badge and some text to Licenses section in readme 

### ISSUE THREAD

**Issue by 1Shubham7** [Yash-Parsana/CrazyCoderApp#90]
### Is your feature request related to a problem? Please describe.

The readme file of the repo should have a Licenses badge and some text regarding licenses in the  Licenses section to make it more professional.

![afters](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/116020663/df57e4ed-2b1c-4236-b95d-17c9f3190e5a)

### Describe the solution you'd like

adding a licenses section

### Additional context

Please assign me this issue under GSSoC'23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Yash-Parsana** [comment]
This issue is not considerable.
Closing it.
