### ISSUE TITLE
<bug>: input for border

### ISSUE THREAD

**Issue by dheeraj1129** [Yash-Parsana/CrazyCoderApp#91]
### Describe the bug

when click on the input form the border line appears

### Expected behaviour

hide the border line

### Screenshots

![Screenshot (103)](https://github.com/Yash-Parsana/CrazyCoderApp/assets/72201773/19872a99-753c-445b-ad06-aab2888eb401)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Yash-Parsana** [comment]
Not Considerable
