### ISSUE TITLE
No Code of Conduct

### ISSUE THREAD

**Issue by Dhruv-Pattel** [Yash-Parsana/CrazyCoderApp#93]
This repository has no code of conduct. any open-source project needs to set clear standards for behavior. It promotes inclusivity, prevents misconduct, fosters accountability, and maintains a positive environment.

Please assign this issue to me.

**Comment by rohitlokhande47** [comment]
I would like to create the Code of Conduct for the given app description #gssoc2024

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.
