### ISSUE TITLE
There is no logout button in application

### ISSUE THREAD

**Issue by maniyaom** [Yash-Parsana/CrazyCoderApp#94]
Add a logout button to the profile section. We can incorporate the logout button to resemble the one displayed in the screenshot.
![WhatsApp Image 2024-05-11 at 18 16 08_da556809](https://github.com/Yash-Parsana/CrazyCoderApp/assets/105499099/1d9bcef3-a5a1-4c8f-856c-ec5429c4073b)

**Comment by maniyaom** [comment]
please assign me this issue under GSOC

**Comment by vardhini3103** [comment]
I want to work on this issue. Please assign this to me.

**Comment by maniyaom** [comment]
I have done this already please assign me. I am left with pull request only. waiting for gsoc label.

**Comment by abhishekkr4747** [comment]
I want to work on this issue. Please assign me

**Comment by Ajay-patidar0** [comment]
I want to work on this issue. Please assign this issue to me. Also add GSSoc24 level in the label.

**Comment by rohitlokhande47** [comment]
I would like to create a log out button for the given app description #gssoc2024

**Comment by Jatinchouhan** [comment]
Log out button seems missing , got to fix it for you . please assign it to me

**Comment by Yash-Parsana** [comment]
@maniyaom Thank you for raising this issue but we don't want to add logout feature.
